spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erna
    username: 'postgres'
    password: 'mysecretpassword'
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: 'create-drop'

  devtools:
    livereload:
      enabled: false